const SPACE_ACCESS_TOKEN="3PJRQW5WYUOHR3UDAPCS"
const SPACE_SECRET="mzBAvFa2dLTdEn6KR0quEP9s4xtmxARmVHPnEBFJ7F0"
const SPACE_ENDPOINT="https://glow-data-storage.fra1.digitaloceanspaces.com"
const SPACE_BUCKET="glow-data-storage"

export {SPACE_ACCESS_TOKEN,SPACE_SECRET,SPACE_ENDPOINT,SPACE_BUCKET}
